name: Push to public repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          # Add your build commands here (e.g., npm run build)

      - name: Push to public repo
        uses: cpina/github-action-push-to-another-repository@v1.2
        with:
          source-dir: 'build'
          destination-git_username: 'BRANCO-TECH'
          destination_git_email: 'mwaleb075@gmail.com'
          destination-repo: 'BRANCO-TECH/Mchinji-Secondary-Web-Portal'
          destination-branch: 'main'
          ssh_key: ${{ secrets.SSH_DEPLOY_KEY }}
          commit-message: Deploy buil to public repo


