name: Push to public repo

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build project
        run: |
          # your build commands here

      - name: Push to another repo
        uses: ad-m/github-push-action@master
        with:
          ssh_key: ${{ secrets.SSH_DEPLOY_KEY }}
          ssh: true
          source: .
          destination: git@github.com:BRANCO-TECH/Mchinji-Secondary-Web-Portal.git
          branch: main
          commit_message: 'Deploy build'
          force: false

